### ISSUE TITLE
insert image to header can not display

### ISSUE THREAD

**Issue by liserjrqlxue** [baliance/gooxml#150]
## Description
I use `AddDrawingInline(iref)` to insert image into the header. But it result can not display the image.

<img width="620" alt="default" src="https://user-images.githubusercontent.com/5977521/35130110-23aa7fea-fcfa-11e7-95f0-199aed44e592.PNG">

## Actual Behavior

The code:
```golang


  img,err:=common.ImageFromFile("header.png")
  if err!=nil{
    log.Fatalf("unable to create image: %s",err)
  }
  iref,err:=doc.AddImage(img)
  if err!=nil{
    log.Fatalf("unable to to add image to document: %s",err)
  }

  version="DX-SDP-B40 V1.3"
  hdr=doc.AddHeader()
  para=hdr.AddParagraph()
  para.AddRun().AddDrawingInline(iref)
  para.AddRun().AddText(version)

  // add page break
  para=doc.AddParagraph()
  section=para.Properties().AddSection(wml.ST_SectionMarkNextPage)
  section.SetHeader(hdr,wml.ST_HdrFtrDefault)
  section.SetFooter(ftr,wml.ST_HdrFtrDefault)
```

**Comment by tbaliance** [comment]
Yeah, we're not handing this correctly.  What's missing is a reference to the image in a header relationships file.  I'll fix this at some point, hopefully soon.

**Comment by tbaliance** [comment]
Give this a shot. Be sure you add the image to the header instead of the document (or add to both).

```
       // We need to add a reference of the image to the header instead of to the
       // document
       iref, err := hdr.AddImage(img)
       if err != nil {
               log.Fatalf("unable to to add image to document: %s", err)
       }
``

```

**Comment by JoeButler99** [comment]
This issue seems to also exist when loading a document which contains an image in the header. 
When I dug into this it seems that the image names within the document have changed, which may or may not be relevant. 

doc, err := document.Open("master/template.docx")   // Image is "media/image1.png", first image in media

doc.SaveToFile("release/test1.docx") // Image is now "media/image10.png" and other images are before
