### ISSUE TITLE
the gooxml only work on windows, on linux it don't work

### ISSUE THREAD

**Issue by systemcia** [baliance/gooxml#254]
## Description
all the examples work well on windows , but on linux some don't work
## Expected Behavior
i have ran the example pdf-export-ole , it's ok on windows , but have error on linux.
## Actual Behavior
1.i've got this error on linux : 
2019/03/27 14:12:02 error creating Word object:
2.by the way the docx can be converted to pdf , can i reverse the pdf to docx ?

**Comment by freb** [comment]
That example can only be run on Windows, see this line: <https://github.com/baliance/gooxml/blob/master/_examples/document/pdf-export-ole/main.go#L14>.

That example requires Word to be installed. I can't speak to whether or not it would work if you installed Word with Wine on Linux since I've never had much luck with that setup.
